evaluation:
  metric: prometheus_eval
  rubric_score:
    # The below statements can change based on the criteria
    # In LangTest, we usually define Pass/Fail criteria for the tests.
    # This is how we adapted the score definitions in Prometheus to align with that approach.
    # Users may modify these definitions to improve evaluations if desired,
    # but the primary goal is to maintain the Pass/Fail consistency required by LangTest.
    'True': >-
      The statement is considered true if the responses remain consistent 
      and convey the same meaning, even when subjected to variations or
      perturbations. Response A should be regarded as the ground truth, and
      Response B should match it in both content and meaning despite any
      changes.
    'False': >-
      The statement is considered false if the responses differ in content 
      or meaning when subjected to variations or perturbations. If 
      Response B fails to match the ground truth (Response A) consistently,
      the result should be marked as false.
tests:
  defaults:
    min_pass_rate: 0.65
  robustness:
    add_ocr_typo:
      min_pass_rate: 0.66
    dyslexia_word_swap:
      min_pass_rate: 0.6